### ISSUE TITLE
How to build This project

### ISSUE THREAD

**Issue by jay51** [skx/assembler#27]
I'm sorry I'm not too familiar with go, especially the package managment part of it. In the build instruction in the README, it says I can clone the repo and do 
```sh   
$ cd cmd/assembler 
$ go build .
```
I'm able to compile the `cmd/lexer` and `cmd/parser` 
but that path `cmd/assembler` doesn't exist.

I'm  confused can you please explain how to build this project?

I'm running inside a docker ubuntu image and go version 1.13.8

**Comment by skx** [comment]
I'm sorry I'd somehow failed to commit that - due to a bogus `.gitignore` file.

You should be able to build now.
